language: objective-c
osx_image: xcode7.2
xcode_project: SWINQ.xcodeproj
xcode_scheme: SWINQ
script: 
  - xcodebuild -enableCodeCoverage YES
  - xctool -project SWINQ.xcodeproj -scheme SWINQ build test -sdk iphonesimulator GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES
after_success:
  - bash <(curl -s https://codecov.io/bash)
